export enum EAction {
  SET_IS_FAVOURITE = "SET_IS_FAVOURITE",
  SET_FILTERED_TEXT = "SET_FILTERED_TEXT",
  SET_SHOW_FAVOURITE = "SET_SHOW_FAVOURITE",
  SET_DISPLAY_FILES_VIEW = "SET_DISPLAY_FILES_VIEW",
  SET_FILTERED_ARRAY_FILE_IDS = "SET_FILTERED_ARRAY_FILE_IDS",
}

export enum EDisplayFileView {
  GRID = "grid",
  LIST = "list",
}
