export enum EAction {
  TOGGLE_SET_FAVOURITE = "TOGGLE_SET_FAVOURITE",
  SET_MULTIPLE_FAVOURITE = "SET_MULTIPLE_FAVOURITE",
  SET_FILTERED_TEXT = "SET_FILTERED_TEXT",
  TOGGLE_SHOW_FAVOURITE = "TOGGLE_SHOW_FAVOURITE",
  SET_DISPLAY_FILES_VIEW = "SET_DISPLAY_FILES_VIEW",
  SET_FILTERED_ARRAY_FILE_IDS = "SET_FILTERED_ARRAY_FILE_IDS",
  DELETE_MULTIPLE_FILES = "DELETE_MULTIPLE_FILES",
}

export enum EDisplayFileView {
  GRID = "grid",
  LIST = "list",
}
